###

GET http://localhost:8080/api/types

###

POST http://localhost:8080/api/appointments
Content-Type: application/json

{
  "taxId": "0123456789",
  "intervall":
     {
       "startTime": "2042-02-01T01:00:00",
       "endTime": "2032-03-01T13:23:12"
     },
  "typeCode": "002"
}
